macx {
#	QMAKE_MAC_SDK = /Developer/SDKs/MacOSX10.4u.sdk
	QMAKE_MAC_SDK = /Developer/SDKs/MacOSX10.5.sdk
	QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.5
#	QMAKE_MACOSX_DEPLOYMENT_TARGET = 10.4
	CONFIG += x86 # x86_64
#	CONFIG += ppc # ppc64
}
